from __future__ import annotations
import argparse
import json
import os

import torch
from torch.utils.data import Dataset

from harness.config import RESULTS_DIR, Config, save_run_settings, set_seeds
from harness.model_io import resolve_device

OUT_DIR = os.path.join(RESULTS_DIR, "distill")
ADAPTER_DIR = os.path.join(OUT_DIR, "lora_adapter")


class PairDataset(Dataset):
    def __init__(self, tokenizer, pairs, max_len=1024):
        self.tok = tokenizer
        self.rows = []
        for p in pairs:
            msgs = p["messages"]
            prompt_text = tokenizer.apply_chat_template(
                msgs[:-1], tokenize=False, add_generation_prompt=True)
            full_text = tokenizer.apply_chat_template(
                msgs, tokenize=False, add_generation_prompt=False)
            p_ids = tokenizer(prompt_text, add_special_tokens=False)["input_ids"]
            f_ids = tokenizer(full_text, add_special_tokens=False)["input_ids"][:max_len]
            labels = list(f_ids)
            for i in range(min(len(p_ids), len(labels))):
                labels[i] = -100
            self.rows.append((f_ids, labels))

    def __len__(self):
        return len(self.rows)

    def __getitem__(self, i):
        ids, labels = self.rows[i]
        return {"input_ids": ids, "labels": labels}


def collate(batch, pad_id):
    maxlen = max(len(b["input_ids"]) for b in batch)
    input_ids, labels, attn = [], [], []
    for b in batch:
        n = maxlen - len(b["input_ids"])
        input_ids.append(b["input_ids"] + [pad_id] * n)
        labels.append(b["labels"] + [-100] * n)
        attn.append([1] * len(b["input_ids"]) + [0] * n)
    return (torch.tensor(input_ids), torch.tensor(labels), torch.tensor(attn))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--epochs", type=int, default=3)
    ap.add_argument("--lr", type=float, default=1e-4)
    ap.add_argument("--batch", type=int, default=2)
    ap.add_argument("--rank", type=int, default=16)
    ap.add_argument("--smoke", type=int, default=0,
                    help="if >0, train only this many steps (roundtrip test)")
    ap.add_argument("--grad_ckpt", action="store_true",
                    help="trade compute for VRAM; needed for 7B on a 24GB card")
    args = ap.parse_args()

    from peft import LoraConfig, get_peft_model
    from transformers import AutoModelForCausalLM, AutoTokenizer

    cfg = Config()
    set_seeds(cfg.seed)
    device = resolve_device(cfg)
    print(f"train_lora: model {cfg.model_id} on {device} "
          f"| batch {args.batch} | rank {args.rank} | epochs {args.epochs}")

    settings_path = os.path.join(OUT_DIR, "distill_data.settings.json")
    if not os.path.isfile(settings_path):
        raise SystemExit(
            f"no {settings_path} — the distillation data carries no teacher "
            f"provenance. Refusing to train: a pairs file from another model would "
            f"be indistinguishable from a fresh one.")
    teacher = json.load(open(settings_path))["config"]["model_id"]
    if teacher != cfg.model_id:
        raise SystemExit(
            f"teacher/student mismatch: distill_pairs.jsonl was generated by "
            f"{teacher} but this run's model is {cfg.model_id}. Distilling across "
            f"scales confounds installation method with scale. Regenerate the data "
            f"(python -m distill.generate_data) or set SL_MODEL_ID={teacher}.")

    pairs = [json.loads(l) for l in open(os.path.join(OUT_DIR, "distill_pairs.jsonl"))]
    tok = AutoTokenizer.from_pretrained(cfg.model_id)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    tdtype = torch.float32 if device == "cpu" else torch.bfloat16
    model = AutoModelForCausalLM.from_pretrained(cfg.model_id, dtype=tdtype)
    lora = LoraConfig(r=args.rank, lora_alpha=args.rank * 2, lora_dropout=0.05,
                      target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
                      task_type="CAUSAL_LM")
    model = get_peft_model(model, lora).to(device)
    for _n, _p in model.named_parameters():
        if _p.requires_grad:
            _p.data = _p.data.to(torch.float32)
    if args.grad_ckpt:
        model.enable_input_require_grads()
        model.gradient_checkpointing_enable()
        model.config.use_cache = False
    model.train()

    ds = PairDataset(tok, pairs)
    opt = torch.optim.AdamW([p for p in model.parameters() if p.requires_grad], lr=args.lr)

    def batches():
        order = torch.randperm(len(ds)).tolist()
        for i in range(0, len(order), args.batch):
            yield collate([ds[j] for j in order[i:i + args.batch]], tok.pad_token_id)

    step, losses = 0, []
    for ep in range(args.epochs):
        for input_ids, labels, attn in batches():
            input_ids, labels, attn = (input_ids.to(device), labels.to(device),
                                        attn.to(device))
            out = model(input_ids=input_ids, attention_mask=attn, labels=labels)
            out.loss.backward()
            opt.step(); opt.zero_grad()
            losses.append(out.loss.item())
            step += 1
            if step % 10 == 0:
                print(f"ep{ep} step{step} loss {out.loss.item():.4f}")
            if args.smoke and step >= args.smoke:
                break
        if args.smoke and step >= args.smoke:
            break

    os.makedirs(ADAPTER_DIR, exist_ok=True)
    model.save_pretrained(ADAPTER_DIR)
    save_run_settings(cfg, os.path.join(OUT_DIR, "lora_train.settings.json"),
                      extra={"epochs": args.epochs, "lr": args.lr, "rank": args.rank,
                             "n_pairs": len(pairs), "final_loss": losses[-1] if losses else None,
                             "smoke": args.smoke, "device": device, "batch": args.batch,
                             "grad_ckpt": args.grad_ckpt, "dtype": str(tdtype)})
    print(f"\nsaved adapter -> {ADAPTER_DIR}  (steps={step}, "
          f"final_loss={losses[-1]:.4f})" if losses else "no steps run")


if __name__ == "__main__":
    main()